stages:
  - test
  - build
  - deploy

variables:
  DOCKER_TLS_CERTDIR: "/certs"

test:
  stage: test
  image: node:20
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  script:
    - npm ci
    - npx tsc --noEmit
    - npm run lint
    - npm run build

docker:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE/backend:latest ./backend
    - docker push $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE/backend:latest


    - docker build -t $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE/frontend:latest .
    - docker push $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE/frontend:latest
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

deploy:
  stage: deploy
  image:
    name: hashicorp/terraform:1.9
    entrypoint: [""]
  before_script:
    - mkdir -p ~/.kube
    - cp "$KUBE_CONFIG" ~/.kube/shop-aws-config
  script:
    - cd IaC/terraform/dev
    - terraform init
    - >
      terraform apply -auto-approve
      -var="backend_image=$CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHORT_SHA"
      -var="frontend_image=$CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHORT_SHA"
      -var="registry_username=$REGISTRY_DEPLOY_USER"
      -var="registry_password=$REGISTRY_DEPLOY_TOKEN"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'